# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'fileutils'

Vagrant.configure(2) do |config|
  config.vm.box = "darwin-yosemite"
  config.vm.box_check_update = false

  config.vm.hostname    = 'puppet-me'
  config.ssh.insert_key = false

  FileUtils.mkdir_p '../../tmp' unless Dir.exist? '../../tmp'
  config.vm.synced_folder "../../config",  "/config"
  config.vm.synced_folder "../../install", "/scripts"
  config.vm.synced_folder "../../tmp",     "/data-tmp"

  config.vm.provider :virtualbox do |provider, override|
    provider.customize ['modifyvm', :id, '--vram',        128]
    provider.customize ['modifyvm', :id, '--clipboard',   'bidirectional']
    provider.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
  end
end
