# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "darwin-yosemite"
  config.vm.box_check_update = false

  config.ssh.insert_key = false

  config.vm.synced_folder "../../config",  "/config"
  config.vm.synced_folder "../../install", "/scripts"
  config.vm.synced_folder "../../tmp",     "/data-tmp"
end
