# -*- mode: ruby -*-
# vi: set ft=ruby :
require 'fileutils'

Vagrant.configure(2) do |config|
  config.vm.box = "daas/windows-8.1"
  config.vm.box_check_update = false

  config.vm.guest             = :windows
  config.windows.halt_timeout = 15
  config.vm.communicator      = 'winrm'

  config.vm.hostname    = 'puppet-me'
  config.winrm.username = 'vagrant'
  config.winrm.password = 'vagrant'

  FileUtils.mkdir_p '../../tmp' unless Dir.exist? '../../tmp'
  config.vm.synced_folder '../../config',    '/config'
  config.vm.synced_folder '../../install',   '/scripts'
  config.vm.synced_folder '../../tmp',       '/data-tmp'
  config.vm.synced_folder '/var/cache/daas', '/daas'

  config.vm.provider :virtualbox do |provider, override|
    provider.customize ['modifyvm', :id, '--vram',        128]
    provider.customize ['modifyvm', :id, '--clipboard',   'bidirectional']
    provider.customize ['modifyvm', :id, '--draganddrop', 'bidirectional']
  end
end
